import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

interface AnalysisResult {
  extractedSkills: string[];
  matchPercentage: number;
  matchingSkills: string[];
  missingSkills: string[];
  similarityScore: number;
  jobRole: string;
  aiSummary: string;
  recommendations: {
    skill: string;
    courses: { name: string; platform: string; url: string }[];
    projects: string[];
    roadmap: { month1: string; month2: string; month3: string };
  }[];
}

interface DownloadReportButtonProps {
  result: AnalysisResult;
  onDownloadComplete?: () => void;
}

export default function DownloadReportButton({ result, onDownloadComplete }: DownloadReportButtonProps) {
  const handleDownload = () => {
    const html = `
<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>SkillGap AI Report</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; }
  h1 { color: #6c3ce0; border-bottom: 3px solid #6c3ce0; padding-bottom: 8px; }
  h2 { color: #333; margin-top: 28px; }
  .stats { display: flex; gap: 20px; margin: 20px 0; }
  .stat { background: #f4f0ff; border-radius: 10px; padding: 16px 24px; text-align: center; flex: 1; }
  .stat-value { font-size: 28px; font-weight: 700; color: #6c3ce0; }
  .stat-label { font-size: 13px; color: #666; }
  .badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 13px; margin: 3px; }
  .badge-match { background: #e0f7e9; color: #1b8a4a; }
  .badge-miss { background: #fde8e8; color: #c0392b; }
  .summary { background: #f4f0ff; border-left: 4px solid #6c3ce0; padding: 14px 18px; border-radius: 6px; margin: 16px 0; }
  .rec { background: #fafafa; border: 1px solid #eee; border-radius: 8px; padding: 14px; margin: 10px 0; }
  .rec h3 { margin: 0 0 8px; color: #6c3ce0; }
  .footer { margin-top: 40px; text-align: center; color: #aaa; font-size: 12px; }
  a { color: #6c3ce0; }
</style></head><body>
<h1>SkillGap AI Report</h1>
<p><strong>Target Role:</strong> ${result.jobRole}</p>
<p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>

${result.aiSummary ? `<div class="summary"><strong>AI Summary:</strong> ${result.aiSummary}</div>` : ""}

<div class="stats">
  <div class="stat"><div class="stat-value">${result.matchPercentage.toFixed(1)}%</div><div class="stat-label">Match Score</div></div>
  <div class="stat"><div class="stat-value">${result.matchingSkills.length}</div><div class="stat-label">Skills Matched</div></div>
  <div class="stat"><div class="stat-value">${result.missingSkills.length}</div><div class="stat-label">Skills to Learn</div></div>
</div>

<h2>Matching Skills</h2>
<div>${result.matchingSkills.map(s => `<span class="badge badge-match">${s}</span>`).join(" ")}</div>

<h2>Missing Skills</h2>
<div>${result.missingSkills.map(s => `<span class="badge badge-miss">${s}</span>`).join(" ")}</div>

${result.recommendations.length > 0 ? `
<h2>Recommendations</h2>
${result.recommendations.map(r => `
<div class="rec">
  <h3>${r.skill}</h3>
  ${r.courses.length > 0 ? `<p><strong>Courses:</strong></p><ul>${r.courses.map(c => `<li><a href="${c.url}">${c.name}</a> (${c.platform})</li>`).join("")}</ul>` : ""}
  ${r.projects.length > 0 ? `<p><strong>Projects:</strong></p><ul>${r.projects.map(p => `<li>${p}</li>`).join("")}</ul>` : ""}
  <p><strong>Roadmap:</strong> Month 1: ${r.roadmap.month1} → Month 2: ${r.roadmap.month2} → Month 3: ${r.roadmap.month3}</p>
</div>`).join("")}` : ""}

<div class="footer">Generated by SkillGap AI</div>
</body></html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `skillgap-report-${result.jobRole.replace(/\s+/g, "-").toLowerCase()}.html`;
    a.click();
    URL.revokeObjectURL(url);

    // Trigger the callback after download
    if (onDownloadComplete) {
      onDownloadComplete();
    }
  };

  return (
    <Button variant="outline" onClick={handleDownload}>
      <Download className="h-4 w-4 mr-2" /> Download Report
    </Button>
  );
}
